# https://taskfile.dev

version: '3'
tasks:
  doc_db:
    cmd: tbls -c .tbls.yml
  doc_api:
    cmds:
      - task: doc_api_html
      - task: doc_api_xml
  doc_api_html:
    cmd: phpdoc run
  doc_api_xml:
    cmd: phpdoc run --template=xml
