---
# code: language=ansible
- name: Setup post create task
  hosts: all
  connection: local
  become: false
  vars:
    base_dir: "{{ ansible_facts.env.PWD | dirname | dirname }}"
    install_tools:
      - osv-scanner
      - delta
      - lazygit
      - task
      - pict
      - duckdb
      - gitleaks
      - github-cli
      - fnt
      - d2
      # - graphviz
      # - plantuml
      - mermaid-cli
      - zx
      - ni
      - phpDocumentor
    github_cli_extensions:
      - github/gh-copilot
  roles:
    - role: tools
      become: true
  tasks:
    - name: Install pip packages
      ansible.builtin.import_tasks:
        file: tasks/pip_package.yml
    - name: Set git setting
      ansible.builtin.import_tasks:
        file: tasks/git.yml
    - name: Set user environment setting
      ansible.builtin.import_tasks:
        file: tasks/environment.yml
    - name: Set bash-completion setting
      ansible.builtin.import_tasks:
        file: tasks/completion.yml
