---
# code: language=ansible
- name: Set eza alias
  ansible.builtin.lineinfile:
    path: ~/.bashrc
    line: alias ls="eza --git --header"
- name: Set lazygit alias
  ansible.builtin.lineinfile:
    path: ~/.bashrc
    line: alias lg="lazygit"
- name: Set copilot alias
  ## @see https://docs.github.com/ja/copilot/managing-copilot/configure-personal-settings/configuring-github-copilot-in-the-cli
  ansible.builtin.lineinfile:
    path: ~/.bashrc
    line: eval "$(gh copilot alias -- bash)"
